'The FlexSearch-Consul.exe will run as a windows service with FlexSearch.exe as
'its dependend service. So, ideally FlexSearch will not run unless Consul is running.
@startuml
start 

:Identify cluster master;
    note right
        See Leader_election logic
    end note
if (Node is cluster master?) then (Yes)
    :Push global settings to consul KV store
        - 'fs/cluster/global';
        note left
            This will load shared location,
            backup location etc
        end note
    : Push all settings to consul KV store
        - Map and filter lists 'fs/lists'
        - Analyzers 'fs/analyzers'
        - Indices Information 'fs/indices';
        note left
            This comes from shared storage
        end note
    : Set Cluster Replication done
        - 'fs/cluster/replication';
        note left
            This can be another key in consul
        end note
else (No)
    while (Cluster Replication is done?) is (No)
        :Retrieve global settings from consul;
        :Retrieve all settings from consul KV store;
    endwhile (Yes)
endif


:Get list of all peers 'status/peers';
:Establish NetMq connections with all peers;
:Check the role of the current node - client, server, data;
:Figure out which indices should be loaded on the given node;
stop
@enduml