@startuml
title Request to master node
autonumber
actor Client
boundary LoadBalancer
database TransactionLog

Client -> LoadBalancer: Request
LoadBalancer -> Beta: indexName:id
Beta -> TransactionLog: Write ahead transaction log
Beta --> Client: success response
Beta --> Alpha: Sync
Beta --> Gamma: Sync
@enduml